# Generated by Django 2.2.2 on 2019-07-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190718_0043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('Category', 'Item_desc', 'Vendor_name', 'Vendor_loc', 'Approval', 'Project')},
        ),
    ]
