# Generated by Django 2.2.2 on 2019-07-30 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190730_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Comm_dept1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Dept1_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
