# Generated by Django 2.2.2 on 2019-07-31 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190730_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Project',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
