# Generated by Django 2.2.2 on 2019-08-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20190806_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Approval',
            field=models.CharField(max_length=100),
        ),
    ]
