# Generated by Django 2.2.2 on 2019-08-21 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20190806_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='Comm_dept1',
            new_name='Commissioning_Comments',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='Dept1_rating',
            new_name='Commissioning_Rating',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='Comm_dept2',
            new_name='Engineering_Comments',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='Dept2_rating',
            new_name='Engineering_Rating',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='Comm_dept3',
            new_name='Erection_Comments',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='Dept3_rating',
            new_name='Erection_Rating',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='Comm_dept4',
            new_name='Finance_Comments',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='Dept4_rating',
            new_name='Finance_Rating',
        ),
        migrations.AddField(
            model_name='vendor',
            name='PMG_Comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='PMG_Rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Quality_Comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Quality_Rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='SCM_Comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='SCM_Rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
